version: "3.9"

services:

  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env  # Use the .env file for environment variables
    environment:
      MYSQL_DATABASE: ratelimiter
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - ratelimiterNetwork

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ratelimiterNetwork

  ratelimiterexample:
    image: 'ratelimiter:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratelimiter
    restart: on-failure
    env_file:
      - .env  # Use the .env file for environment variables
    ports:
      - "1224:1224"
    environment:
      - server.port=1224
      - spring.datasource.username=${DATABASE_USERNAME}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - SECURITY_DB_IP=database
      - SECURITY_DB_PORT=3307
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/ratelimiter
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
      - redis
    networks:
      - ratelimiterNetwork

networks:
  ratelimiterNetwork: